spring.application.name=evidence-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/evidence_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.kafka.producer.bootstrap-servers=localhost:9092

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

resilience4j.circuitbreaker.instances.caseService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.caseService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.caseService.sliding-window-size=10
