spring.application.name=case-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/case_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.kafka.producer.bootstrap-servers=localhost:9092
