spring.application.name=audit-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/audit_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-group
spring.kafka.consumer.auto-offset-reset=earliest
